apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: demo-manual-pipeline-run
spec:
  params:
  - name: event-type
    value: push
  - name: event-ref
    value: refs/heads/master
  - name: docker-imagename
    value: demo-image
  - name: docker-imagetag
    value: latest
  serviceAccountName: kabanero-pipeline
  timeout: "1h0m0s"
  pipelineRef:
    name: java-spring-boot2-build-deploy-pl
  resources:
    - name: git-source
      resourceRef:
        name: git-source
    - name: docker-image
      resourceRef:
        name: docker-image